# Generated by Django 4.2.3 on 2023-07-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0002_usertask"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile",
            field=models.ImageField(null=True, upload_to="profile"),
        ),
    ]
